### ISSUE TITLE
Can you upgrade robotframework to the latest version?

### ISSUE THREAD

**Issue by nottyo** [jspringbot/jspringbot#6]
Robotframework released the new major version (robotframework 3.0) since the end of last year. Could you please upgrade the jspringbot framework to use robotframework 3.0? You can see some new features of robotframework 3.0 here https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.0.rst Thank you

**Comment by badong2210** [comment]
We are working on it. Thank you.

**Comment by nottyo** [comment]
Thank you so much :) Really appreciated.

**Comment by shiela-mnltech** [comment]
Updated JSpringBot to use robotframework 3.0.

**Comment by badong2210** [comment]
Updated JSpringBot to use robotframework 3.0.

**Comment by nottyo** [comment]
Thanks so much. I'll try it!

**Comment by alvinrdeleon** [comment]
Its already there. the version to use is 1.5.

**Comment by alvinrdeleon** [comment]
Use this as parent:

```
  <parent>
    <groupId>org.jspringbot</groupId>
    <artifactId>jspringbot-base</artifactId>
    <version>1.5</version>
  </parent>
```

Closing since this is already done.
